### PR TITLE
fix: correctly validate token

### PR DESCRIPTION
**Pull request by drazisil-codecov**

### CODE REVIEW

**Review by thomasrockhu — APPROVED** [review]
Dat formatting though

**Comment by RA80533** [comment]
> > Dat formatting though
> 
> I don't even know what formatter that is anymore. Every time I blink I swear VSCode changes it on me.

Related #210

**Comment by RA80533** [comment]
Per https://github.com/codecov/uploader/pull/212#issuecomment-881623245:

> The token is exposed as part of the destination for the HTTP/HTTPS request being sent. Since the destinations must be parsed in order to route them along to the destination itself, each node along the route a given request takes will see the token. This happens even if the request is sent using HTTPS.
> 
> /cc @drazisil @drazisil-codecov @vlad-ko

**Comment by RA80533** [comment]
If a source-level modification is required for operation to occur, should the change be made at the backend in such a way to not require this vulnerability to exist?

**Comment by RA80533** [comment]
> The token is only able to upload coverage reports, nothing else, so it is not a sensitive as an API token.

Ah, I believe I understand. Just to reiterate, the token is associated with a specific coverage report and is not an authoritative credential of the user uploading the report? In other words, if I were to send a request with the token as it is logged in the CI, there would be additional authentication measures in place to prevent me from impersonating the uploader?

**Pull request merged**
